GETSP _MEMORY_SIZE SWAP SAVE 
_main CALL 
GETRV HALT 
:_MEMORY_SIZE 0 
:_PROGRAM_SIZE PROGRAM_SIZE 

:_out 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD OUT 
:__out 
GETFP SETSP SETFP 
1 RETN 

:_getFP 
GETFP GETSP SETFP 
GETFP SETRV __getFP JMP 
:__getFP 
GETFP SETSP SETFP 
JMP 

:_printInt 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD 
10 
CMP _true_if_0_printInt JGE 
_exit_if_0_printInt JMP 
:_true_if_0_printInt 
GETFP 2 ADD LOAD 10 DIV _printInt CALL GETRV DROP 
:_exit_if_0_printInt 
GETFP 2 ADD LOAD 10 MOD 48 ADD _out CALL GETRV DROP 
:__printInt 
GETFP SETSP SETFP 
1 RETN 

:_newLine 
GETFP GETSP SETFP 
10 _out CALL GETRV DROP 
:__newLine 
GETFP SETSP SETFP 
JMP 

:_Point2__setX 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD 1 ADD GETFP 3 ADD LOAD SAVE 
:__Point2__setX 
GETFP SETSP SETFP 
2 RETN 

:_Point2__setY 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD 2 ADD GETFP 3 ADD LOAD SAVE 
:__Point2__setY 
GETFP SETSP SETFP 
2 RETN 

:_Point2__getX 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD 1 ADD LOAD SETRV __Point2__getX JMP 
:__Point2__getX 
GETFP SETSP SETFP 
1 RETN 

:_Point2__getY 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD 2 ADD LOAD SETRV __Point2__getY JMP 
:__Point2__getY 
GETFP SETSP SETFP 
1 RETN 

:_Point2_vtbl__ 
_Point2__setX _Point2__setY _Point2__getX _Point2__getY 

:_main 
GETFP GETSP SETFP 
GETFP GETSP SETFP 
3 PUSHN 
GETFP 3 SUB _Point2_vtbl__ SAVE 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB GETFP LOAD 3 SUB SAVE 
100500 GETFP 1 SUB LOAD GETFP 1 SUB LOAD LOAD 1 ADD LOAD CALL GETRV SETRV GETFP SETSP SETFP 
GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB GETFP LOAD 3 SUB SAVE 
1501 GETFP 1 SUB LOAD GETFP 1 SUB LOAD LOAD 0 ADD LOAD CALL GETRV SETRV GETFP SETSP SETFP 
GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB GETFP LOAD 3 SUB SAVE 
GETFP 1 SUB LOAD GETFP 1 SUB LOAD LOAD 2 ADD LOAD CALL GETRV SETRV GETFP SETSP SETFP 
GETRV _printInt CALL GETRV DROP 
_newLine CALL GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB GETFP LOAD 3 SUB SAVE 
GETFP 1 SUB LOAD GETFP 1 SUB LOAD LOAD 3 ADD LOAD CALL GETRV SETRV GETFP SETSP SETFP 
GETRV _printInt CALL GETRV DROP 
GETFP SETSP SETFP 
0 SETRV __main JMP 
:__main 
GETFP SETSP SETFP 
JMP 


