GETSP _MEMORY_SIZE SWAP SAVE 
_main CALL 
GETRV HALT 
:_MEMORY_SIZE 0 
:_PROGRAM_SIZE PROGRAM_SIZE 

:_inc__ 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD GETFP 2 ADD LOAD LOAD 1 ADD SAVE 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __inc__ JMP 
:__inc__ 
GETFP SETSP SETFP 
1 RETN 

:_dec__ 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD GETFP 2 ADD LOAD LOAD 1 SUB SAVE 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __dec__ JMP 
:__dec__ 
GETFP SETSP SETFP 
1 RETN 

:_heap_order__ 
3 

:_heap_start__ 
0 

:_getHeapBlock__ 
GETFP GETSP SETFP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB _PROGRAM_SIZE LOAD GETFP LOAD 2 ADD LOAD 3 SUB ADD SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __getHeapBlock__ JMP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __getHeapBlock__ JMP 
:__getHeapBlock__ 
GETFP SETSP SETFP 
1 RETN 

:_getNextBlock__ 
GETFP GETSP SETFP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB GETFP LOAD 2 ADD LOAD 1 ADD LOAD SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __getNextBlock__ JMP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __getNextBlock__ JMP 
:__getNextBlock__ 
GETFP SETSP SETFP 
1 RETN 

:_unlinkBlock__ 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 1 SUB GETFP 2 ADD LOAD 0 ADD LOAD SAVE 
GETFP 2 SUB GETFP 2 ADD LOAD 1 ADD LOAD SAVE 
GETFP 1 SUB LOAD 
0 
CMP _true_if_0_unlinkBlock__ JNE 
_false_if_0_unlinkBlock__ JMP 
:_true_if_0_unlinkBlock__ 
GETFP 1 SUB LOAD 1 ADD GETFP 2 SUB LOAD SAVE 
_exit_if_0_unlinkBlock__ JMP 
:_false_if_0_unlinkBlock__ 
GETFP 2 ADD LOAD 2 ADD LOAD _getHeapBlock__ CALL GETRV GETFP 2 SUB LOAD SAVE 
:_exit_if_0_unlinkBlock__ 
GETFP 2 SUB LOAD 
0 
CMP _true_if_1_unlinkBlock__ JNE 
_exit_if_1_unlinkBlock__ JMP 
:_true_if_1_unlinkBlock__ 
GETFP 2 SUB LOAD 0 ADD GETFP 1 SUB LOAD SAVE 
:_exit_if_1_unlinkBlock__ 
GETFP 2 ADD LOAD 3 ADD 1 SAVE 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __unlinkBlock__ JMP 
:__unlinkBlock__ 
GETFP SETSP SETFP 
1 RETN 

:_linkBlocks__ 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD 
0 
CMP _true_if_0_linkBlocks__ JNE 
_exit_if_0_linkBlocks__ JMP 
:_true_if_0_linkBlocks__ 
GETFP 2 ADD LOAD 1 ADD GETFP 3 ADD LOAD SAVE 
:_exit_if_0_linkBlocks__ 
GETFP 3 ADD LOAD 
0 
CMP _true_if_1_linkBlocks__ JNE 
_exit_if_1_linkBlocks__ JMP 
:_true_if_1_linkBlocks__ 
GETFP 3 ADD LOAD 0 ADD GETFP 2 ADD LOAD SAVE 
:_exit_if_1_linkBlocks__ 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __linkBlocks__ JMP 
:__linkBlocks__ 
GETFP SETSP SETFP 
2 RETN 

:_insertBlock__ 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB GETFP 2 ADD LOAD 2 ADD LOAD _getHeapBlock__ CALL GETRV SAVE 
GETFP 1 SUB LOAD LOAD GETFP 2 ADD LOAD _linkBlocks__ CALL GETRV DROP 
GETFP 2 ADD LOAD 0 ADD 0 SAVE 
GETFP 2 ADD LOAD 3 ADD 0 SAVE 
GETFP 1 SUB LOAD GETFP 2 ADD LOAD SAVE 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __insertBlock__ JMP 
:__insertBlock__ 
GETFP SETSP SETFP 
1 RETN 

:_splitBlock__ 
GETFP GETSP SETFP 
3 PUSHN 
GETFP 2 ADD LOAD _unlinkBlock__ CALL GETRV DROP 
GETFP 1 SUB GETFP 2 ADD LOAD 2 ADD LOAD 1 SUB SAVE 
GETFP 2 SUB GETFP 2 ADD LOAD 1 GETFP 1 SUB LOAD LSHIFT ADD SAVE 
GETFP 2 ADD LOAD 2 ADD GETFP 1 SUB LOAD SAVE 
GETFP 2 SUB LOAD 2 ADD GETFP 1 SUB LOAD SAVE 
GETFP 2 SUB LOAD _insertBlock__ CALL GETRV DROP 
GETFP 2 ADD LOAD _insertBlock__ CALL GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __splitBlock__ JMP 
:__splitBlock__ 
GETFP SETSP SETFP 
1 RETN 

:_unionBlock__ 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 2 ADD LOAD 3 ADD LOAD 
1 
CMP _true_if_0_unionBlock__ JEQ 
_exit_if_0_unionBlock__ JMP 
:_true_if_0_unionBlock__ 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __unionBlock__ JMP 
:_exit_if_0_unionBlock__ 
GETFP 2 ADD LOAD _heap_start__ LOAD SUB 1 GETFP 2 ADD LOAD 2 ADD LOAD LSHIFT BITAND 
0 
CMP _true_if_1_unionBlock__ JEQ 
_false_if_1_unionBlock__ JMP 
:_true_if_1_unionBlock__ 
GETFP 1 SUB GETFP 2 ADD LOAD 1 GETFP 2 ADD LOAD 2 ADD LOAD LSHIFT ADD SAVE 
_exit_if_1_unionBlock__ JMP 
:_false_if_1_unionBlock__ 
GETFP 1 SUB GETFP 2 ADD LOAD SAVE 
GETFP 2 ADD GETFP 2 ADD LOAD 1 GETFP 2 ADD LOAD 2 ADD LOAD LSHIFT SUB SAVE 
:_exit_if_1_unionBlock__ 
GETFP 1 SUB LOAD 3 ADD LOAD 
1 
CMP _true_if_2_unionBlock__ JEQ 
_bool_0_unionBlock__ JMP 
:_bool_0_unionBlock__ 
GETFP 2 ADD LOAD 2 ADD LOAD 
GETFP 1 SUB LOAD 2 ADD LOAD 
CMP _true_if_2_unionBlock__ JNE 
_exit_if_2_unionBlock__ JMP 

:_true_if_2_unionBlock__ 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __unionBlock__ JMP 
:_exit_if_2_unionBlock__ 
GETFP 2 ADD LOAD _unlinkBlock__ CALL GETRV DROP 
GETFP 1 SUB LOAD _unlinkBlock__ CALL GETRV DROP 
GETFP 2 ADD LOAD 2 ADD _inc__ CALL GETRV DROP 
GETFP 2 ADD LOAD _insertBlock__ CALL GETRV DROP 
GETFP 2 ADD LOAD _unionBlock__ CALL GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __unionBlock__ JMP 
:__unionBlock__ 
GETFP SETSP SETFP 
1 RETN 

:_allocBlock__ 
GETFP GETSP SETFP 
3 PUSHN 
GETFP 1 SUB 3 SAVE 
:_loop_while_0_allocBlock__ 
GETFP 2 ADD LOAD 
1 GETFP 1 SUB LOAD LSHIFT 1 3 LSHIFT SUB 
CMP _true_while_0_allocBlock__ JGT 
_exit_while_0_allocBlock__ JMP 
:_true_while_0_allocBlock__ 
GETFP 1 SUB _inc__ CALL GETRV DROP 
_loop_while_0_allocBlock__ JMP 
:_exit_while_0_allocBlock__ 
GETFP 2 SUB GETFP 1 SUB LOAD SAVE 
:_loop_while_1_allocBlock__ 
GETFP 2 SUB LOAD _getHeapBlock__ CALL GETRV LOAD 
0 
CMP _true_while_1_allocBlock__ JEQ 
_exit_while_1_allocBlock__ JMP 
:_true_while_1_allocBlock__ 
GETFP 2 SUB _inc__ CALL GETRV DROP 
GETFP 2 SUB LOAD 
_heap_order__ LOAD 
CMP _true_if_0_allocBlock__ JGT 
_exit_if_0_allocBlock__ JMP 
:_true_if_0_allocBlock__ 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __allocBlock__ JMP 
:_exit_if_0_allocBlock__ 
_loop_while_1_allocBlock__ JMP 
:_exit_while_1_allocBlock__ 
:_loop_while_2_allocBlock__ 
GETFP 2 SUB LOAD 
GETFP 1 SUB LOAD 
CMP _true_while_2_allocBlock__ JNE 
_exit_while_2_allocBlock__ JMP 
:_true_while_2_allocBlock__ 
GETFP 2 SUB LOAD _getHeapBlock__ CALL GETRV LOAD _splitBlock__ CALL GETRV DROP 
GETFP 2 SUB _dec__ CALL GETRV DROP 
_loop_while_2_allocBlock__ JMP 
:_exit_while_2_allocBlock__ 
GETFP 3 SUB GETFP 1 SUB LOAD _getHeapBlock__ CALL GETRV LOAD SAVE 
GETFP 3 SUB LOAD _unlinkBlock__ CALL GETRV DROP 
GETFP 3 SUB GETFP 3 SUB LOAD 1 3 LSHIFT ADD SAVE 
GETFP 3 SUB LOAD 1 SUB 1 SAVE 
GETFP 3 SUB LOAD 2 SUB 0 SAVE 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB GETFP LOAD 3 SUB LOAD SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __allocBlock__ JMP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __allocBlock__ JMP 
:__allocBlock__ 
GETFP SETSP SETFP 
1 RETN 

:_deallocBlock__ 
GETFP GETSP SETFP 
GETFP 2 ADD GETFP 2 ADD LOAD 1 3 LSHIFT SUB SAVE 
GETFP 2 ADD LOAD _insertBlock__ CALL GETRV DROP 
GETFP 2 ADD LOAD _unionBlock__ CALL GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __deallocBlock__ JMP 
:__deallocBlock__ 
GETFP SETSP SETFP 
1 RETN 

:_out__ 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD OUT 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __out__ JMP 
:__out__ 
GETFP SETSP SETFP 
1 RETN 

:_printInt__ 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD 
10 
CMP _true_if_0_printInt__ JGE 
_exit_if_0_printInt__ JMP 
:_true_if_0_printInt__ 
GETFP 2 ADD LOAD 10 DIV _printInt__ CALL GETRV DROP 
:_exit_if_0_printInt__ 
GETFP 2 ADD LOAD 10 MOD 48 ADD _out__ CALL GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __printInt__ JMP 
:__printInt__ 
GETFP SETSP SETFP 
1 RETN 

:_newLine__ 
GETFP GETSP SETFP 
10 _out__ CALL GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __newLine__ JMP 
:__newLine__ 
GETFP SETSP SETFP 
JMP 

:_space__ 
GETFP GETSP SETFP 
32 _out__ CALL GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __space__ JMP 
:__space__ 
GETFP SETSP SETFP 
JMP 

:_printHeap__ 
GETFP GETSP SETFP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 3 SAVE 
:_loop_while_0_printHeap__ 
GETFP 1 SUB LOAD 
_heap_order__ LOAD 
CMP _true_while_0_printHeap__ JLE 
_exit_while_0_printHeap__ JMP 
:_true_while_0_printHeap__ 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB 0 SAVE 
GETFP 1 SUB GETFP LOAD 1 SUB LOAD _getHeapBlock__ CALL GETRV LOAD SAVE 
:_loop_while_1_printHeap__ 
GETFP 1 SUB LOAD 
0 
CMP _true_while_1_printHeap__ JNE 
_exit_while_1_printHeap__ JMP 
:_true_while_1_printHeap__ 
GETFP 2 SUB _inc__ CALL GETRV DROP 
GETFP 1 SUB GETFP 1 SUB LOAD _getNextBlock__ CALL GETRV SAVE 
_loop_while_1_printHeap__ JMP 
:_exit_while_1_printHeap__ 
GETFP 2 SUB LOAD _printInt__ CALL GETRV DROP 
_space__ CALL GETRV DROP 
GETFP SETSP SETFP 
GETFP 1 SUB _inc__ CALL GETRV DROP 
_loop_while_0_printHeap__ JMP 
:_exit_while_0_printHeap__ 
_newLine__ CALL GETRV DROP 
GETFP SETSP SETFP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __printHeap__ JMP 
:__printHeap__ 
GETFP SETSP SETFP 
JMP 

:_refInc__ 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD 
0 
CMP _true_if_0_refInc__ JNE 
_exit_if_0_refInc__ JMP 
:_true_if_0_refInc__ 
GETFP 2 ADD LOAD 1 SUB _inc__ CALL GETRV DROP 
:_exit_if_0_refInc__ 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __refInc__ JMP 
:__refInc__ 
GETFP SETSP SETFP 
1 RETN 

:_refDec__ 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD 
0 
CMP _true_if_0_refDec__ JNE 
_exit_if_0_refDec__ JMP 
:_true_if_0_refDec__ 
GETFP 2 ADD LOAD 1 SUB _dec__ CALL GETRV DROP 
GETFP 2 ADD LOAD 1 SUB LOAD 
0 
CMP _true_if_1_refDec__ JEQ 
_exit_if_1_refDec__ JMP 
:_true_if_1_refDec__ 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB GETFP LOAD 2 ADD LOAD 2 SUB LOAD SAVE 
GETFP 1 SUB 0 SAVE 
:_loop_while_0_refDec__ 
GETFP 1 SUB LOAD 
GETFP 2 SUB LOAD 
CMP _true_while_0_refDec__ JNE 
_exit_while_0_refDec__ JMP 
:_true_while_0_refDec__ 
GETFP LOAD 2 ADD LOAD GETFP 1 SUB LOAD ADD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB _inc__ CALL GETRV DROP 
_loop_while_0_refDec__ JMP 
:_exit_while_0_refDec__ 
GETFP SETSP SETFP 
GETFP 2 ADD LOAD _deallocBlock__ CALL GETRV DROP 
:_exit_if_1_refDec__ 
:_exit_if_0_refDec__ 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __refDec__ JMP 
:__refDec__ 
GETFP SETSP SETFP 
1 RETN 

:_genNode 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB GETFP LOAD 1 SUB SAVE 
GETFP 1 SUB LOAD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD 2 _allocBlock__ CALL GETRV SAVE 
GETFP 1 SUB LOAD LOAD 2 SUB 1 SAVE 
GETFP SETSP SETFP 
GETFP 1 SUB LOAD 0 ADD 0 SAVE 
GETFP 1 SUB LOAD 1 ADD GETFP 2 ADD LOAD SAVE 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB GETFP LOAD 1 SUB LOAD SAVE 
GETFP 1 SUB LOAD _refInc__ CALL GETRV DROP 
GETFP LOAD 1 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __genNode JMP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP LOAD 1 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __genNode JMP 
:__genNode 
GETFP SETSP SETFP 
1 RETN 

:_linkNodes 
GETFP GETSP SETFP 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB GETFP LOAD 3 ADD LOAD SAVE 
GETFP 1 SUB GETFP LOAD 2 ADD LOAD 0 ADD SAVE 
GETFP 2 SUB LOAD _refInc__ CALL GETRV DROP 
GETFP 1 SUB LOAD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD GETFP 2 SUB LOAD SAVE 
GETFP SETSP SETFP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __linkNodes JMP 
:__linkNodes 
GETFP SETSP SETFP 
2 RETN 

:_printLinkedList 
GETFP GETSP SETFP 
:_loop_while_0_printLinkedList 
GETFP 2 ADD LOAD 
0 
CMP _true_while_0_printLinkedList JNE 
_exit_while_0_printLinkedList JMP 
:_true_while_0_printLinkedList 
GETFP 2 ADD LOAD 1 ADD LOAD _printInt__ CALL GETRV DROP 
_space__ CALL GETRV DROP 
GETFP 2 ADD GETFP 2 ADD LOAD 0 ADD LOAD SAVE 
_loop_while_0_printLinkedList JMP 
:_exit_while_0_printLinkedList 
_newLine__ CALL GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __printLinkedList JMP 
:__printLinkedList 
GETFP SETSP SETFP 
1 RETN 

:_main 
GETFP GETSP SETFP 
4 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP 2 SUB 0 SAVE 
GETFP 3 SUB 0 SAVE 
GETFP 4 SUB 0 SAVE 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 1 SUB 1 3 LSHIFT SAVE 
GETFP 2 SUB _MEMORY_SIZE LOAD _PROGRAM_SIZE LOAD 64 ADD SUB SAVE 
_heap_order__ LOAD _getHeapBlock__ CALL GETRV 0 SAVE 
:_loop_while_0_main 
GETFP 1 SUB LOAD 
GETFP 2 SUB LOAD 
CMP _true_while_0_main JLE 
_exit_while_0_main JMP 
:_true_while_0_main 
_heap_order__ LOAD _getHeapBlock__ CALL GETRV 0 SAVE 
_heap_order__ _inc__ CALL GETRV DROP 
GETFP 1 SUB GETFP 1 SUB LOAD 1 LSHIFT SAVE 
_loop_while_0_main JMP 
:_exit_while_0_main 
_heap_order__ _dec__ CALL GETRV DROP 
GETFP SETSP SETFP 
_heap_start__ _heap_order__ LOAD _getHeapBlock__ CALL GETRV 1 ADD SAVE 
_heap_start__ LOAD 2 ADD _heap_order__ LOAD SAVE 
_heap_start__ LOAD _insertBlock__ CALL GETRV DROP 
_printHeap__ CALL GETRV DROP 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB 100500 _genNode CALL GETRV SAVE 
GETFP 1 SUB GETFP LOAD 2 SUB SAVE 
GETFP 1 SUB LOAD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD GETFP 2 SUB LOAD SAVE 
GETFP SETSP SETFP 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB 1501 _genNode CALL GETRV SAVE 
GETFP 1 SUB GETFP LOAD 3 SUB SAVE 
GETFP 1 SUB LOAD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD GETFP 2 SUB LOAD SAVE 
GETFP SETSP SETFP 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB 666 _genNode CALL GETRV SAVE 
GETFP 1 SUB GETFP LOAD 4 SUB SAVE 
GETFP 1 SUB LOAD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD GETFP 2 SUB LOAD SAVE 
GETFP SETSP SETFP 
GETFP 3 SUB LOAD GETFP 2 SUB LOAD _linkNodes CALL GETRV DROP 
GETFP 4 SUB LOAD GETFP 3 SUB LOAD _linkNodes CALL GETRV DROP 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB GETFP LOAD 3 SUB LOAD SAVE 
GETFP 1 SUB GETFP LOAD 1 SUB SAVE 
GETFP 2 SUB LOAD _refInc__ CALL GETRV DROP 
GETFP 1 SUB LOAD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD GETFP 2 SUB LOAD SAVE 
GETFP SETSP SETFP 
GETFP 2 SUB LOAD _printLinkedList CALL GETRV DROP 
GETFP 3 SUB LOAD _printLinkedList CALL GETRV DROP 
GETFP 4 SUB LOAD _printLinkedList CALL GETRV DROP 
GETFP 1 SUB LOAD _printLinkedList CALL GETRV DROP 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB 0 SAVE 
GETFP 1 SUB GETFP LOAD 2 SUB SAVE 
GETFP 2 SUB LOAD _refInc__ CALL GETRV DROP 
GETFP 1 SUB LOAD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD GETFP 2 SUB LOAD SAVE 
GETFP SETSP SETFP 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB 0 SAVE 
GETFP 1 SUB GETFP LOAD 3 SUB SAVE 
GETFP 2 SUB LOAD _refInc__ CALL GETRV DROP 
GETFP 1 SUB LOAD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD GETFP 2 SUB LOAD SAVE 
GETFP SETSP SETFP 
GETFP GETSP SETFP 
2 PUSHN 
GETFP 2 SUB 0 SAVE 
GETFP 1 SUB GETFP LOAD 4 SUB SAVE 
GETFP 2 SUB LOAD _refInc__ CALL GETRV DROP 
GETFP 1 SUB LOAD LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD GETFP 2 SUB LOAD SAVE 
GETFP SETSP SETFP 
_printHeap__ CALL GETRV DROP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP LOAD 1 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP LOAD 2 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP LOAD 3 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP LOAD 4 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __main JMP 
GETFP GETSP SETFP 
1 PUSHN 
GETFP 1 SUB 0 SAVE 
GETFP LOAD 1 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP LOAD 2 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP LOAD 3 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP LOAD 4 SUB LOAD _refDec__ CALL GETRV DROP 
GETFP 1 SUB LOAD SETRV GETFP SETSP SETFP 
GETRV SETRV __main JMP 
:__main 
GETFP SETSP SETFP 
JMP 


