GETSP _MEMORY_SIZE SWAP SAVE 
_main CALL 
GETRV HALT 
:_MEMORY_SIZE 0 
:_PROGRAM_SIZE PROGRAM_SIZE 

:_out 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD OUT 
:__out 
GETFP SETSP SETFP 
1 RETN 

:_square 
GETFP GETSP SETFP 
GETFP 2 ADD LOAD GETFP 2 ADD LOAD MUL SETRV __square JMP 
:__square 
GETFP SETSP SETFP 
1 RETN 

:_main 
GETFP GETSP SETFP 
97 5 _square CALL GETRV ADD _out CALL GETRV DROP 
0 SETRV __main JMP 
:__main 
GETFP SETSP SETFP 
JMP 


